import {randomUUID} from "node:crypto";
import {mkdtemp,rm} from "node:fs/promises";
import {tmpdir} from "node:os";
import path from "node:path";
import {createServer, type Server} from "node:http";
import express from "express";
import mysql, {type Pool} from "mysql2/promise";
import {drizzle} from "drizzle-orm/mysql2";
import {migrate} from "drizzle-orm/mysql2/migrator";
import {eq} from "drizzle-orm";
import {afterAll,beforeAll,describe,it,expect,vi} from "vitest";
import {users,apiCredentials,conversationTurns,localAssets,deliveryProjectAssignments,enterpriseProjectDashboardContents} from "../drizzle/schema";
import {knowledgeBaseLocalUploadHeaders} from "../shared/knowledge-base-local-upload";
import {createDefaultDashboardPayload} from "../shared/dashboard";
const state=vi.hoisted(()=>({db:null as any}));
vi.mock("../server/db",()=>({getDb:async()=>state.db}));
const base=process.env.FRONTMIND_KB_MANUS_V2_MYSQL_ACCEPTANCE_DATABASE_URL;
if(process.env.FRONTMIND_KB_MANUS_V2_MYSQL_ACCEPTANCE_REQUIRED === "1" && !base) throw new Error("KB_SCOPE_MYSQL_REQUIRED");
describe.skipIf(!base)("real authenticated project upload transactions",()=>{
 let pool:Pool,server:Server,origin:string,assets:string,owner:any,admin:any,engineer:any,outsider:any,projectA:any,projectB:any;
 const cookies=new Map<number,string>();
 const credentialId=randomUUID();
 const previousKey=process.env.FRONTMIND_CREDENTIAL_ENCRYPTION_KEY,previousAssets=process.env.FRONTMIND_DASHBOARD_ASSET_DIR;
 const request=async(projectId:string,route:string,body?:any,actor=owner)=>{
   const response=await fetch(`${origin}/api/knowledge-base${route}`,{method:body?"POST":"GET",headers:{cookie:cookies.get(actor.id)!,"x-enterprise-project-id":projectId,...(body?{"content-type":"application/json"}:{})},...(body?{body:JSON.stringify(body)}:{})});
   return {status:response.status,body:await response.json() as any};
 };
 beforeAll(async()=>{
   const url=new URL(base!);if(url.protocol !== "mysql:" || !/^\w*frontmind_kb_acceptance\w*$/.test(url.pathname.slice(1)))throw new Error("DISPOSABLE_DATABASE_REQUIRED");
   const name=`frontmind_kb_acceptance_scope_${Date.now()}`;url.pathname="/";
   const connection=await mysql.createConnection(url.toString());await connection.query(`CREATE DATABASE \`${name}\``);await connection.end();url.pathname=`/${name}`;
   pool=mysql.createPool({uri:url.toString(),connectionLimit:12});state.db=drizzle(pool);
   await migrate(state.db,{migrationsFolder:path.resolve("drizzle")});
   process.env.FRONTMIND_CREDENTIAL_ENCRYPTION_KEY=`base64:${Buffer.alloc(32,86).toString("base64")}`;
   assets=await mkdtemp(path.join(tmpdir(),"kb-upload-scope-"));process.env.FRONTMIND_DASHBOARD_ASSET_DIR=assets;
   const {createSession,encryptApiKey}=await import("../server/auth-service");
   for(const [name,role,level,engineerRole] of [["owner","user",null,null],["admin","admin","system_admin",null],["engineer","delivery_member",null,"ai_operations_engineer"],["outsider","user",null,null]] as const){
     const result=await state.db.insert(users).values({openId:randomUUID(),username:`scope-${name}-${Date.now()}`,displayName:name,role,adminAccessLevel:level,engineerRoleType:engineerRole,isActive:true});
     const [row]=await state.db.select().from(users).where(eq(users.id,result[0].insertId));
     if(name==="owner")owner=row;else if(name==="admin")admin=row;else if(name==="engineer")engineer=row;else outsider=row;
     cookies.set(row.id,`app_session_id=${(await createSession(row.id)).token}`);
   }
   await state.db.insert(deliveryProjectAssignments).values({id:randomUUID(),customerUserId:owner.id,engineerUserId:engineer.id,roleType:"ai_operations_engineer",assignedByUserId:admin.id});
   await state.db.insert(apiCredentials).values({id:credentialId,userId:owner.id,version:1,provider:"zhipu",...encryptApiKey(owner.id,credentialId,"isolated-synthetic-key"),fingerprint:"a".repeat(12),status:"active",validationStatus:"verified"});
   const {createEnterpriseProject}=await import("../server/enterprise-project-service");
   projectA=await createEnterpriseProject(owner,{name:"合成企业甲",clientRequestId:randomUUID()});projectB=await createEnterpriseProject(owner,{name:"合成企业乙",clientRequestId:randomUUID()});
   for(const project of [projectA,projectB])await state.db.update(enterpriseProjectDashboardContents).set({payload:createDefaultDashboardPayload(project.name),enterpriseIdentityBoundAt:new Date()}).where(eq(enterpriseProjectDashboardContents.enterpriseProjectId,project.id));
   const {ensureDashboardAccountLink}=await import("../../../packages/monitoring-db/src/dashboard-account-links");const link=await ensureDashboardAccountLink(state.db,owner.id);
   await pool.execute("UPDATE unified_money_wallets SET balance_ten_thousandths=100000000 WHERE user_id=?",[link.monitoringUserId]);
   const {requireExpressAuth,attachOptionalActiveCredential}=await import("../server/_core/express-auth");
   const {default:kb}=await import("../server/knowledge-base-api");const {default:chat}=await import("../server/frontmind-v2-chat-router");
   const {enforceDeliveryProjectContext,rejectDeliveryMemberKnowledgeBaseProjectScope}=await import("../server/_core/frontmind-proxy-policy");
   const app=express();app.use(express.json());app.use("/api/knowledge-base",requireExpressAuth,enforceDeliveryProjectContext,rejectDeliveryMemberKnowledgeBaseProjectScope,attachOptionalActiveCredential,kb);app.use("/api/frontmind/v2",requireExpressAuth,attachOptionalActiveCredential,chat);
   server=createServer(app);await new Promise<void>(resolve=>server.listen(0,"127.0.0.1",resolve));origin=`http://127.0.0.1:${(server.address() as any).port}`;
 },300000);
 afterAll(async()=>{if(server)await new Promise<void>(resolve=>server.close(()=>resolve()));if(pool)await pool.end();if(assets)await rm(assets,{recursive:true,force:true});if(previousKey===undefined)delete process.env.FRONTMIND_CREDENTIAL_ENCRYPTION_KEY;else process.env.FRONTMIND_CREDENTIAL_ENCRYPTION_KEY=previousKey;if(previousAssets===undefined)delete process.env.FRONTMIND_DASHBOARD_ASSET_DIR;else process.env.FRONTMIND_DASHBOARD_ASSET_DIR=previousAssets;});
 it("keeps real identity, retained bytes, stop/resume, credential rotation and reset boundaries",async()=>{
   const bytes=Buffer.from("合成企业甲成立于2020年，产品为资料归档软件，服务覆盖三个城市。\n");
   const conversationId=`scope-${randomUUID()}`,clientRequestId=randomUUID();
   const manifest=[{itemId:randomUUID(),ordinal:1,total:1,filename:"企业资料.txt",sizeBytes:bytes.length,mimeType:"text/plain",lastModified:1}];
   const reserved=await request(projectA.id,"/start/reserve",{conversationId,clientRequestId,companyName:projectA.name,attachmentManifest:manifest,expectedResetRevision:0},admin);
   expect([200,201,202],JSON.stringify(reserved.body)).toContain(reserved.status);
   const turnId=reserved.body.reservation.turnId,attempt=reserved.body.reservation.uploadAttemptId;
   expect(attempt).toEqual(expect.any(String));
   const coordinates={conversationId,turnId,clientRequestId,expectedResetRevision:0,uploadAttemptId:attempt};
   const statusRoute=`/turn/upload-status?${new URLSearchParams({conversationId,turnId,clientRequestId,expectedResetRevision:"0"})}`;
   const findRoute=`/turn/upload-status?${new URLSearchParams({conversationId,clientRequestId,expectedResetRevision:"0"})}`;
   const found=await request(projectA.id,findRoute);
   expect(found.status,JSON.stringify(found.body)).toBe(200);
   expect(found.body.reservation).toMatchObject({turnId,clientRequestId,uploadAttemptId:attempt,generation:reserved.body.reservation.generation,revision:reserved.body.reservation.revision,leafId:reserved.body.reservation.leafId});
   expect((await request(projectB.id,findRoute)).status).toBe(404);
   expect((await request(projectA.id,statusRoute,undefined,outsider)).status).toBe(404);
   expect((await request(projectB.id,statusRoute)).status).toBe(404);
   expect((await request(projectA.id,statusRoute,undefined,engineer)).status).toBe(200);
   const snapshot=await state.db.select().from(conversationTurns).where(eq(conversationTurns.id,turnId));
   expect(snapshot[0].conversationId).toBe(`e${projectA.id}:${conversationId}`);
   await request(projectA.id,statusRoute);
   const afterRead=await state.db.select().from(conversationTurns).where(eq(conversationTurns.id,turnId));expect(afterRead).toEqual(snapshot);
   const upload=async(attemptId:string)=>fetch(`${origin}/api/frontmind/v2/assets`,{method:"POST",headers:{cookie:cookies.get(owner.id)!,"x-enterprise-project-id":projectA.id,"content-type":"application/octet-stream","x-frontmind-filename":encodeURIComponent(manifest[0].filename),"x-frontmind-mime":"text/plain","x-frontmind-size":String(bytes.length),...knowledgeBaseLocalUploadHeaders({...coordinates,itemId:manifest[0].itemId,ordinal:1,uploadAttemptId:attemptId},1)},body:bytes});
   const accepted=await upload(attempt);expect(accepted.status,await accepted.clone().text()).toBe(201);const asset=await accepted.json() as any;
   const [assetRow]=await state.db.select().from(localAssets).where(eq(localAssets.id,asset.localAssetId));expect(assetRow.enterpriseProjectId).toBe(projectA.id);
   expect((await request(projectA.id,statusRoute)).body.files[0].status).toBe("retained");
   const stopped=await request(projectA.id,"/turn/upload-control",{...coordinates,action:"stop"});expect(stopped.body.controlState).toBe("stopped");
   expect(stopped.body).toMatchObject({runPhase:"cancelled",createAttemptState:"not_sent",dispatchRecoveryAction:"none",knowledgeObservation:{runPhase:"cancelled"}});
   const {listCustomerAiUsage}=await import("../server/customer-ai-usage");
   const stoppedUsage=await listCustomerAiUsage(owner,{page:1,enterpriseProjectId:projectA.id});
   expect(stoppedUsage.tasks.find(task=>task.buildId===stopped.body.buildId && task.generation===stopped.body.generation)).toMatchObject({status:"已停止",phase:"上传已停止，未产生模型调用",currentTurnInvocationState:"not_sent",usageStatus:"none",chargedTenThousandths:"0"});
   expect((await request(projectA.id,"/turn/upload-heartbeat",{...coordinates,status:"active",uploadedBytes:bytes.length})).status).toBe(409);
   expect((await request(projectA.id,"/turn/attachments/resume",coordinates)).status).toBe(409);
   expect((await upload(attempt)).status).toBe(409);
   expect((await request(projectA.id,statusRoute)).body.controlState).toBe("stopped");
   const resumed=await request(projectA.id,"/turn/upload-control",{...coordinates,action:"resume"});const newAttempt=resumed.body.uploadAttemptId;expect(newAttempt).not.toBe(attempt);
   expect((await upload(attempt)).status).toBe(409);
   const replay=await upload(newAttempt);expect(replay.status).toBe(200);expect((await replay.json() as any).localAssetId).toBe(asset.localAssetId);
   const staged=await request(projectA.id,"/turn/attachments/resume",{...coordinates,uploadAttemptId:newAttempt});expect(staged.status,JSON.stringify(staged.body)).toBe(200);
   const complete=await request(projectA.id,statusRoute);expect(complete.body).toMatchObject({confirmedFiles:1,confirmedBytes:bytes.length,totalFiles:1,readyToDispatch:true,runPhase:"staging"});
   expect(complete.body).toMatchObject({createAttemptState:"not_sent",dispatchRecoveryAction:"safe_dispatch",knowledgeObservation:{runPhase:"staging"}});
   const {runWithEnterpriseProjectScope}=await import("../server/enterprise-project-context");const {resolveEnterpriseProjectScope}=await import("../server/enterprise-project-service");const scope=await resolveEnterpriseProjectScope(engineer,projectA.id);
   await state.db.update(apiCredentials).set({status:"retired"}).where(eq(apiCredentials.id,credentialId));
   const {getDecryptedCredentialForKnowledgeBaseUploadReservation}=await import("../server/auth-service");
   expect(await runWithEnterpriseProjectScope(scope,()=>getDecryptedCredentialForKnowledgeBaseUploadReservation({userId:owner.id,conversationId,turnId}))).toMatchObject({id:credentialId,status:"retired"});
   await state.db.update(apiCredentials).set({status:"deleted"}).where(eq(apiCredentials.id,credentialId));
   await expect(runWithEnterpriseProjectScope(scope,()=>getDecryptedCredentialForKnowledgeBaseUploadReservation({userId:owner.id,conversationId,turnId}))).rejects.toMatchObject({code:"INVALID_CREDENTIAL"});
   const {resetKnowledgeBase}=await import("../server/knowledge-base-reset-service");
   await runWithEnterpriseProjectScope(scope,()=>resetKnowledgeBase({actor:engineer,expectedRevision:0}));
   expect((await request(projectA.id,statusRoute)).status).toBe(409);
   expect((await request(projectA.id,"/turn/upload-control",{...coordinates,uploadAttemptId:newAttempt,action:"resume"})).status).toBe(409);
   const [terminal]=await state.db.select().from(conversationTurns).where(eq(conversationTurns.id,turnId));expect(terminal.upstreamTaskId).toBeNull();
 },120000);
});
