import { mkdtemp, readFile, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";

import { afterEach, beforeEach, describe, expect, it } from "vitest";

import {
  persistKnowledgeBaseBuildSource,
  persistKnowledgeBaseGeneratedSource,
  persistKnowledgeBaseSkillArchive,
  readKnowledgeBaseLocalSource,
} from "./knowledge-base-local-source-store";

describe("knowledge-base immutable local sources", () => {
  let assetRoot: string;
  let previous: string | undefined;

  beforeEach(async () => {
    previous = process.env.FRONTMIND_DASHBOARD_ASSET_DIR;
    assetRoot = await mkdtemp(path.join(os.tmpdir(), "kb-source-store-"));
    process.env.FRONTMIND_DASHBOARD_ASSET_DIR = assetRoot;
  });

  afterEach(async () => {
    if (previous === undefined)
      delete process.env.FRONTMIND_DASHBOARD_ASSET_DIR;
    else process.env.FRONTMIND_DASHBOARD_ASSET_DIR = previous;
    await rm(assetRoot, { recursive: true, force: true });
  });

  it("installs generated bytes before provider work and pins a build-owned copy", async () => {
    const bytes = Buffer.from("immutable generated instructions", "utf8");
    const crashCopy = await persistKnowledgeBaseGeneratedSource(bytes);
    expect(await readFile(path.join(assetRoot, crashCopy.storageKey))).toEqual(
      bytes,
    );

    const retained = await persistKnowledgeBaseBuildSource({
      userId: 7,
      buildId: "00000000-0000-4000-8000-000000000007",
      generation: 2,
      bytes,
    });
    expect(retained.storageKey).toContain(
      "knowledge-base/build-sources/7/00000000-0000-4000-8000-000000000007/g2/",
    );
    await expect(readKnowledgeBaseLocalSource(retained)).resolves.toEqual(
      bytes,
    );
  });

  it("rejects a descriptor whose SHA or byte count does not match storage", async () => {
    const retained = await persistKnowledgeBaseBuildSource({
      userId: 7,
      buildId: "00000000-0000-4000-8000-000000000007",
      generation: 2,
      bytes: Buffer.from("fixed bytes", "utf8"),
    });
    await expect(
      readKnowledgeBaseLocalSource({
        ...retained,
        contentSha256: "f".repeat(64),
      }),
    ).rejects.toMatchObject({ code: "INTEGRITY_MISMATCH" });
  });

  it("retains Skill archives under a controlled content-addressed key", async () => {
    const bytes = Buffer.from("immutable Skill archive bytes", "utf8");
    const retained = await persistKnowledgeBaseSkillArchive(bytes);

    expect(path.isAbsolute(retained.storageKey)).toBe(false);
    expect(retained.storageKey).toMatch(
      /^knowledge-base\/skill-archives\/[a-f0-9]{64}\.skill\.zip$/u,
    );
    await expect(readKnowledgeBaseLocalSource(retained)).resolves.toEqual(
      bytes,
    );
  });
});
