/**
 * Immutable input coordinates for the FrontMind 2.8 Template catalog.
 *
 * These rows are a frozen projection of 21st's included/recommended lane on
 * 2026-08-28. Runtime customer requests must never refresh or reorder them.
 * The seed command downloads the exact immutable GitHub commit and preview for
 * every row, then records the resulting byte hashes in the active manifest.
 */

export const STATIC_TEMPLATE_CATALOG_WORKFLOW_VERSION = "2.8.0" as const;
export const STATIC_TEMPLATE_CATALOG_VERSION =
  "21st-included-recommended-20260828-v2" as const;
export const STATIC_TEMPLATE_CATALOG_PAGE_SIZE = 8 as const;
export const STATIC_TEMPLATE_CATALOG_PAGE_COUNT = 4 as const;
export const STATIC_TEMPLATE_CATALOG_ENTRY_COUNT = 32 as const;

export type FrozenStaticTemplateDefinition = Readonly<{
  order: number;
  candidateId: string;
  providerTemplateId: string;
  providerSlug: string;
  providerName: string;
  providerDescription: string;
  previewUrl: string;
  sourceOwner: string;
  sourceRepo: string;
  sourceCommitSha: string;
  sourceSubdirectory: string | null;
  sourceLicense: "MIT" | "Apache-2.0";
  tags: readonly string[];
}>;

type FrozenRow = readonly [
  providerTemplateId: number,
  providerSlug: string,
  providerName: string,
  providerDescription: string,
  previewUrl: string,
  sourceOwner: string,
  sourceRepo: string,
  sourceCommitSha: string,
  sourceSubdirectory: string | null,
  sourceLicense: "MIT" | "Apache-2.0",
  tags: readonly string[],
];

const FROZEN_ROWS: readonly FrozenRow[] = [
  [
    827,
    "arfazrll-portfolio",
    "Arfazrll Portfolio",
    "Immersive AI engineer portfolio with WebGL scenes, technical case studies, bilingual content, live GitHub and WakaTime stats, and a dual-provider AI chatbot.",
    "https://cdn.21st.dev/user_2nElBLvklOKlAURm6W1PTu6yYFh/templates/arfazrll-portfolio/preview-20260826111207.png",
    "Arfazrll",
    "PersonalBlog",
    "61354972fbea4f1f9f7007a256488f305e3fa3e7",
    null,
    "MIT",
    ["portfolio", "ai", "personal-website"],
  ],
  [
    825,
    "open-agents",
    "Open Agents",
    "Open-source cloud agent template with durable execution, sandboxed tools, streaming activity and a polished web interface.",
    "https://cdn.21st.dev/user_2nElBLvklOKlAURm6W1PTu6yYFh/templates/open-agents/preview-frame-1b85637a8f.jpg",
    "vercel-labs",
    "open-agents",
    "cf865e94de7729751c747171785b6ce57e7b178c",
    null,
    "MIT",
    ["ai", "workflow", "automation"],
  ],
  [
    824,
    "paddle-billing-starter",
    "Paddle Billing Starter",
    "Complete Next.js SaaS starter with Supabase authentication, localized Paddle pricing, checkout, subscription management and webhook synchronization.",
    "https://cdn.21st.dev/user_3A4LSkyZ3ogOIVqgGoSYFRwuShm/templates/paddle-billing-starter/preview-frame-5fab5752fa.jpg",
    "PaddleHQ",
    "paddle-nextjs-starter-kit",
    "a8c5168e5411af7a4a4c8521d0a8a342ce0307ac",
    null,
    "Apache-2.0",
    ["authentication", "saas", "subscription", "billing"],
  ],
  [
    812,
    "vetra",
    "Vetra",
    "Animated landing page for an AI marketing automation platform, built with Next.js, Tailwind CSS and Framer Motion.",
    "https://cdn.21st.dev/user_2nElBLvklOKlAURm6W1PTu6yYFh/templates/vetra/preview-frame-8a29a47cb7.jpg",
    "Shreyas-29",
    "vetra",
    "1b4d6614d4d7d523ea47ea64ab5ce0bd2b52b692",
    null,
    "MIT",
    ["landing-page", "ai", "saas"],
  ],
  [
    811,
    "luro-ai",
    "Luro AI",
    "AI-powered social media marketing landing page with analytics, campaign insights and polished motion throughout.",
    "https://cdn.21st.dev/user_2nElBLvklOKlAURm6W1PTu6yYFh/templates/luro-ai/preview-frame-fc4adbb164.jpg",
    "Shreyas-29",
    "luro-ai",
    "efd0f6092f1cdd0bfafa976b59d51822ce3e111c",
    null,
    "MIT",
    ["landing-page", "ai", "marketing"],
  ],
  [
    810,
    "orb-ui",
    "orb-ui",
    "React voice AI component library with adapters for Vapi, ElevenLabs, LiveKit, Pipecat, OpenAI Realtime, and Gemini Live.",
    "https://cdn.21st.dev/user_2nElBLvklOKlAURm6W1PTu6yYFh/templates/orb-ui/preview-frame-4dfde68ce1.jpg",
    "alexanderqchen",
    "orb-ui",
    "93a87fa98f4048aac3cc14fc8fe1c48b865a275f",
    null,
    "MIT",
    ["voice", "ai", "react"],
  ],
  [
    809,
    "ai-elements",
    "AI Elements",
    "A component library and custom registry built on top of shadcn/ui to help you build AI-native applications faster.",
    "https://cdn.21st.dev/user_2nElBLvklOKlAURm6W1PTu6yYFh/templates/ai-elements/preview-frame-2ab583990d.jpg",
    "vercel",
    "ai-elements",
    "0c1f5e8c75273f0e95c8faa031544a8aa2bb1a5b",
    null,
    "Apache-2.0",
    ["shadcn", "ai", "react"],
  ],
  [
    808,
    "chanhdai-portfolio",
    "Chanh Dai Portfolio",
    "Pixel-perfect developer portfolio and shadcn registry in one Next.js app, with an interactive profile, MDX blog and component showcase.",
    "https://cdn.21st.dev/user_2xinnI75Qf12K3Et3dvJlqCNjMq/templates/chanhdai-portfolio/preview-frame-cfcf64b8e6.jpg",
    "ncdai",
    "chanhdai.com",
    "e5f3b7855a1688e9f12c7966087c1d1f51ecd86d",
    null,
    "MIT",
    ["portfolio", "personal-website"],
  ],
  [
    807,
    "pixel-point-agency",
    "Pixel Point Agency",
    "The production site of a web agency, on Gatsby and React, with services pages, case studies and a long-running blog.",
    "https://cdn.21st.dev/user_vendor_pixelpoint/templates/pixel-point-agency/preview-frame-b912d6d23a.jpg",
    "pixel-point",
    "pixelpoint-website",
    "80a86baf0b1ea109f2d692e19792466440702775",
    null,
    "MIT",
    ["marketing", "agency"],
  ],
  [
    806,
    "samuelkraft-portfolio-blog",
    "Samuel Kraft Portfolio",
    "Designer portfolio and blog on Next.js, Tailwind and MDX, with tagged writing, project case studies and interaction experiments.",
    "https://cdn.21st.dev/user_vendor_samuelkraft/templates/samuelkraft-portfolio-blog/preview-frame-c82aa35aa7.jpg",
    "samuelkraft",
    "samuelkraft-next",
    "cd735941f511f52ec79079900eb014f3092a4bc1",
    null,
    "MIT",
    ["blog", "portfolio"],
  ],
  [
    804,
    "schdesign-studio",
    "Schdesign Studio",
    "Design studio site on Next.js 15 and React 19, with a painted wordmark hero, work grid, team, about and order pages.",
    "https://cdn.21st.dev/user_vendor_schdesign/templates/schdesign-studio/preview-frame-b0d5dd01d2.jpg",
    "simonyiszk",
    "schdesign-web",
    "d18bdf06e224dd8c994fe5b31e837157cb963661",
    null,
    "MIT",
    ["portfolio", "agency"],
  ],
  [
    803,
    "maxleiter-personal-site",
    "Max Leiter Personal Site",
    "Developer personal site laid out as a desktop, with folders for writing and projects plus a working terminal and calculator.",
    "https://cdn.21st.dev/user_vendor_maxleiter/templates/maxleiter-personal-site/preview-frame-ccd6671ab3.jpg",
    "MaxLeiter",
    "maxleiter.com",
    "013aa158096089388c852355c0c53a97cdd89193",
    null,
    "MIT",
    ["blog", "personal-website"],
  ],
  [
    802,
    "macos-desktop-portfolio",
    "macOS Desktop Portfolio",
    "Personal site built as a whole macOS desktop with draggable windows, a dock, menu bar and several working desktop apps.",
    "https://cdn.21st.dev/user_vendor_alanagoyal/templates/macos-desktop-portfolio/preview-frame-7595833c56.jpg",
    "alanagoyal",
    "alanagoyal",
    "7435666feb2ab20e36501254398c27cc5990792e",
    null,
    "MIT",
    ["portfolio", "personal-website"],
  ],
  [
    801,
    "kintaro-awwwards-portfolio",
    "Kintaro Awwwards Portfolio",
    "Awwwards-style personal portfolio on Next.js and React with smooth scrolling, physics micro-interactions, themes and multilingual content.",
    "https://cdn.21st.dev/user_vendor_xkintaro/templates/kintaro-awwwards-portfolio/preview-frame-a1558013c0.jpg",
    "xkintaro",
    "kintarowwwards",
    "addd7d0806497ef0820b4ebc851fb7f4dcf81498",
    null,
    "MIT",
    ["portfolio", "personal-website"],
  ],
  [
    797,
    "hirael-nexacore",
    "NexaCore",
    "Light enterprise-infrastructure landing page with a floating navbar, video hero, service grid and delivery staircase.",
    "https://cdn.21st.dev/user_2nElBLvklOKlAURm6W1PTu6yYFh/templates/hirael-nexacore/preview-frame.jpg",
    "MohammadShehadeh",
    "hirael",
    "85b198f0ab19238ac3bdfe410cd9766d065b1974",
    "registry/hirael/templates/nexacore",
    "MIT",
    ["landing-page", "saas"],
  ],
  [
    796,
    "hirael-asme",
    "Asme",
    "Dark liquid-glass marketing landing page with a video hero, frosted navigation and scroll-revealed service sections.",
    "https://cdn.21st.dev/user_2nElBLvklOKlAURm6W1PTu6yYFh/templates/hirael-asme/preview-frame.jpg",
    "MohammadShehadeh",
    "hirael",
    "85b198f0ab19238ac3bdfe410cd9766d065b1974",
    "registry/hirael/templates/asme",
    "MIT",
    ["landing-page", "marketing"],
  ],
  [
    795,
    "hirael-velorah",
    "Velorah",
    "Dark premium electric-RV landing page with liquid-glass navigation, feature tabs, streaming video and preorder call to action.",
    "https://cdn.21st.dev/user_2nElBLvklOKlAURm6W1PTu6yYFh/templates/hirael-velorah/preview-frame.jpg",
    "MohammadShehadeh",
    "hirael",
    "85b198f0ab19238ac3bdfe410cd9766d065b1974",
    "registry/hirael/templates/velorah",
    "MIT",
    ["landing-page", "marketing"],
  ],
  [
    794,
    "hirael-rivr",
    "Rivr",
    "DeFi staking landing page with a rounded video hero, glass stat cards, metrics band and bento feature grid.",
    "https://cdn.21st.dev/user_2nElBLvklOKlAURm6W1PTu6yYFh/templates/hirael-rivr/preview-frame.jpg",
    "MohammadShehadeh",
    "hirael",
    "85b198f0ab19238ac3bdfe410cd9766d065b1974",
    "registry/hirael/templates/rivr",
    "MIT",
    ["landing-page", "startup"],
  ],
  [
    793,
    "hirael-usd-halo",
    "USD Halo",
    "Premium fintech landing page for a stablecoin, with a full-bleed video hero, product cards, marquees and dark anchor footer.",
    "https://cdn.21st.dev/user_2nElBLvklOKlAURm6W1PTu6yYFh/templates/hirael-usd-halo/preview-frame.jpg",
    "MohammadShehadeh",
    "hirael",
    "85b198f0ab19238ac3bdfe410cd9766d065b1974",
    "registry/hirael/templates/usd-halo",
    "MIT",
    ["landing-page", "startup"],
  ],
  [
    792,
    "hirael-portfolio",
    "Portfolio",
    "Dark single-page personal portfolio with a video hero, bento work grid, journal, parallax gallery and video contact footer.",
    "https://cdn.21st.dev/user_2nElBLvklOKlAURm6W1PTu6yYFh/templates/hirael-portfolio/preview-frame.jpg",
    "MohammadShehadeh",
    "hirael",
    "85b198f0ab19238ac3bdfe410cd9766d065b1974",
    "registry/hirael/templates/portfolio",
    "MIT",
    ["portfolio", "personal-website"],
  ],
  [
    791,
    "hirael-mindloop",
    "Mindloop",
    "Dark monochrome newsletter landing page with a full-screen video hero, subscribe form and streaming-video call to action.",
    "https://cdn.21st.dev/user_2nElBLvklOKlAURm6W1PTu6yYFh/templates/hirael-mindloop/preview-frame.jpg",
    "MohammadShehadeh",
    "hirael",
    "85b198f0ab19238ac3bdfe410cd9766d065b1974",
    "registry/hirael/templates/mindloop",
    "MIT",
    ["landing-page", "marketing"],
  ],
  [
    790,
    "hirael-agency-landing",
    "Agency Landing",
    "Bright shader-lit agency landing page with animated WebGL hero, editorial sections, video work cards and a dark footer.",
    "https://cdn.21st.dev/user_2nElBLvklOKlAURm6W1PTu6yYFh/templates/hirael-agency-landing/preview-frame.jpg",
    "MohammadShehadeh",
    "hirael",
    "85b198f0ab19238ac3bdfe410cd9766d065b1974",
    "registry/hirael/templates/agency-landing",
    "MIT",
    ["landing-page", "agency"],
  ],
  [
    781,
    "hirael-creative-studio",
    "Creative Studio",
    "Dark cinematic creative-studio landing page with an animated hero, pull-up wordmark and staggered feature grid.",
    "https://cdn.21st.dev/user_2nElBLvklOKlAURm6W1PTu6yYFh/templates/hirael-creative-studio/preview-frame.jpg",
    "MohammadShehadeh",
    "hirael",
    "85b198f0ab19238ac3bdfe410cd9766d065b1974",
    "registry/hirael/templates/creative-studio",
    "MIT",
    ["landing-page", "agency"],
  ],
  [
    778,
    "photography-portfolio",
    "Photography Portfolio",
    "Photography portfolio with photo management, interactive EXIF maps, Drizzle and Postgres.",
    "https://cdn.21st.dev/user_2nElBLvklOKlAURm6W1PTu6yYFh/templates/photography-portfolio/preview-frame.jpg",
    "ECarry",
    "photography-website",
    "4e26e4c15646174c319238b033406cfd1b5c1fe2",
    null,
    "MIT",
    ["portfolio", "personal-website"],
  ],
  [
    777,
    "saas-landing-template",
    "SaaS Landing Template",
    "SaaS landing page on Next.js, shadcn/ui and Tailwind v4, with pricing, feature grid and a built-in dark theme.",
    "https://cdn.21st.dev/user_2nElBLvklOKlAURm6W1PTu6yYFh/templates/saas-landing-template/preview-frame.jpg",
    "gonzalochale",
    "saas-landing-template",
    "7bc36b2a7ae905314c6b7fc95e0168ce5bf0db49",
    null,
    "MIT",
    ["landing-page", "saas"],
  ],
  [
    776,
    "shadcn-dashboard-landing",
    "Shadcn Dashboard and Landing",
    "Admin dashboard plus a matching landing page, shipped in both Next.js and Vite variants of the same design.",
    "https://cdn.21st.dev/user_2nElBLvklOKlAURm6W1PTu6yYFh/templates/shadcn-dashboard-landing/preview-frame.jpg",
    "shadcnstore",
    "shadcn-dashboard-landing-template",
    "65fc11224e96d56a62e224a58f7ed590aea5ac24",
    null,
    "MIT",
    ["dashboard", "landing-page"],
  ],
  [
    775,
    "next-shadcn-admin-dashboard",
    "Next Shadcn Admin Dashboard",
    "Admin dashboard on Next.js and shadcn/ui with multiple layouts, auth screens, data tables and theme presets.",
    "https://cdn.21st.dev/user_2nElBLvklOKlAURm6W1PTu6yYFh/templates/next-shadcn-admin-dashboard/preview-frame.jpg",
    "arhamkhnz",
    "next-shadcn-admin-dashboard",
    "6dd9ab0416ec4d289645456f99dbee043aeaf900",
    null,
    "MIT",
    ["dashboard", "admin-panel"],
  ],
  [
    774,
    "shadcn-saas-landing",
    "Shadcn SaaS Landing",
    "Next.js SaaS landing page with independently removable sections, shadcn/ui and Tailwind throughout.",
    "https://cdn.21st.dev/user_2nElBLvklOKlAURm6W1PTu6yYFh/templates/shadcn-saas-landing/preview-frame.jpg",
    "nobruf",
    "shadcn-landing-page",
    "ec8e18e8ed56ed6636023ced09948515c19258cc",
    null,
    "MIT",
    ["landing-page", "saas"],
  ],
  [
    773,
    "shadcn-landing-page",
    "Shadcn Landing Page",
    "Classic marketing landing page with hero, features, pricing, testimonials, FAQ and footer.",
    "https://cdn.21st.dev/user_2nElBLvklOKlAURm6W1PTu6yYFh/templates/shadcn-landing-page/preview-frame.jpg",
    "leoMirandaa",
    "shadcn-landing-page",
    "ae3716dbce5c8a26815222bb743994b5717938f1",
    null,
    "MIT",
    ["landing-page", "marketing"],
  ],
  [
    772,
    "open-saas",
    "Open SaaS",
    "Full SaaS starter on React, Node and Prisma with authentication, payments, admin dashboard, AI examples and a blog.",
    "https://cdn.21st.dev/user_2nElBLvklOKlAURm6W1PTu6yYFh/templates/open-saas/preview-frame.jpg",
    "wasp-lang",
    "open-saas",
    "cbd30162b05d798b3a3f955ab5781940b67bec89",
    "template",
    "MIT",
    ["authentication", "boilerplate", "saas"],
  ],
  [
    335,
    "chatbot",
    "AI Chatbot",
    "Vercel's full-featured AI chatbot with AI SDK, streaming, tool calls, authentication and persistent chat history.",
    "https://cdn.21st.dev/user_2nElBLvklOKlAURm6W1PTu6yYFh/templates/chatbot/preview-frame.jpg",
    "vercel",
    "chatbot",
    "c2f8235e1f3ea903ad8b7f61447c4f74164b5c58",
    null,
    "Apache-2.0",
    ["chat", "ai", "boilerplate"],
  ],
  [
    5,
    "portfolio-template",
    "Magic UI Portfolio",
    "Minimalist developer portfolio on Next.js, Tailwind, shadcn/ui and Magic UI, driven by a single CV configuration.",
    "https://cdn.21st.dev/user_2vgPxqtXOGc4iU0CBJH2MQn2eTG/templates/portfolio-template/preview-frame.jpg",
    "magicuidesign",
    "portfolio",
    "5ef12e4c8bd0de3e22e89c2181ee77a35925ec8b",
    null,
    "MIT",
    ["portfolio", "personal-website"],
  ],
] as const;

export const FROZEN_STATIC_TEMPLATE_CATALOG: readonly FrozenStaticTemplateDefinition[] =
  Object.freeze(
    FROZEN_ROWS.map((row, index) =>
      Object.freeze({
        order: index + 1,
        candidateId: `static-template-${String(index + 1).padStart(2, "0")}-${row[1]}`,
        providerTemplateId: String(row[0]),
        providerSlug: row[1],
        providerName: row[2],
        providerDescription: row[3],
        previewUrl: row[4],
        sourceOwner: row[5],
        sourceRepo: row[6],
        sourceCommitSha: row[7],
        sourceSubdirectory: row[8],
        sourceLicense: row[9],
        tags: Object.freeze([...row[10]]),
      }),
    ),
  );

if (
  FROZEN_STATIC_TEMPLATE_CATALOG.length !== STATIC_TEMPLATE_CATALOG_ENTRY_COUNT
) {
  throw new Error("STATIC_TEMPLATE_CATALOG_DEFINITION_COUNT_INVALID");
}
