CREATE TABLE `website_manual_service_orders` (
	`id` varchar(36) NOT NULL,
	`schemaVersion` int unsigned NOT NULL DEFAULT 1,
	`idempotencyKeyHash` varchar(64) NOT NULL,
	`requestHash` varchar(64) NOT NULL,
	`projectId` varchar(80) NOT NULL,
	`companyName` varchar(200) NOT NULL,
	`contractProfile` json NOT NULL,
	`serviceCategory` enum('product_scenario','reputation','competitor_comparison') NOT NULL,
	`planCode` enum('basic') NOT NULL DEFAULT 'basic',
	`serviceDays` int unsigned NOT NULL DEFAULT 30,
	`questionId` varchar(80) NOT NULL,
	`question` text NOT NULL,
	`amountFen` int unsigned NOT NULL,
	`contractTemplateVersion` varchar(64) NOT NULL,
	`externalContractId` varchar(128),
	`signingUrl` varchar(2048),
	`signedPdfFileId` varchar(255),
	`signedPdfFilename` varchar(512),
	`signedPdfSha256` varchar(64),
	`evidenceReportFileId` varchar(255),
	`evidenceReportFilename` varchar(512),
	`evidenceReportSha256` varchar(64),
	`signedAt` timestamp,
	`signatoryId` varchar(128),
	`signatureNote` text,
	`paymentIdempotencyKeyHash` varchar(64),
	`paymentRequestHash` varchar(64),
	`paymentOrderId` varchar(64),
	`paymentTradeNo` varchar(128),
	`paidAt` timestamp,
	`accountMode` enum('create','bind_existing'),
	`requestedUsername` varchar(64),
	`requestedDisplayName` varchar(128),
	`provisioningReference` varchar(128),
	`status` enum('pending_admin','signature_required','payment_required','activation_required','active','rejected','failed') NOT NULL DEFAULT 'pending_admin',
	`preparedByUserId` int,
	`signedByUserId` int,
	`activatedByUserId` int,
	`rejectedByUserId` int,
	`preparedAt` timestamp,
	`activatedAt` timestamp,
	`rejectedAt` timestamp,
	`lastError` text,
	`revision` int unsigned NOT NULL DEFAULT 1,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `website_manual_service_orders_id` PRIMARY KEY(`id`),
	CONSTRAINT `website_manual_service_orders_idempotencyKeyHash_unique` UNIQUE(`idempotencyKeyHash`),
	CONSTRAINT `website_manual_service_orders_externalContractId_unique` UNIQUE(`externalContractId`),
	CONSTRAINT `website_manual_service_orders_signedPdfFileId_unique` UNIQUE(`signedPdfFileId`),
	CONSTRAINT `website_manual_service_orders_paymentIdempotencyKeyHash_unique` UNIQUE(`paymentIdempotencyKeyHash`),
	CONSTRAINT `website_manual_service_orders_paymentOrderId_unique` UNIQUE(`paymentOrderId`),
	CONSTRAINT `website_manual_service_orders_paymentTradeNo_unique` UNIQUE(`paymentTradeNo`),
	CONSTRAINT `website_manual_service_orders_provisioningReference_unique` UNIQUE(`provisioningReference`)
);
--> statement-breakpoint
ALTER TABLE `website_manual_service_orders` ADD CONSTRAINT `website_manual_service_orders_preparedByUserId_users_id_fk` FOREIGN KEY (`preparedByUserId`) REFERENCES `users`(`id`) ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `website_manual_service_orders` ADD CONSTRAINT `website_manual_service_orders_signedByUserId_users_id_fk` FOREIGN KEY (`signedByUserId`) REFERENCES `users`(`id`) ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `website_manual_service_orders` ADD CONSTRAINT `website_manual_service_orders_activatedByUserId_users_id_fk` FOREIGN KEY (`activatedByUserId`) REFERENCES `users`(`id`) ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `website_manual_service_orders` ADD CONSTRAINT `website_manual_service_orders_rejectedByUserId_users_id_fk` FOREIGN KEY (`rejectedByUserId`) REFERENCES `users`(`id`) ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX `manual_service_orders_project_idx` ON `website_manual_service_orders` (`projectId`);--> statement-breakpoint
CREATE INDEX `manual_service_orders_status_created_idx` ON `website_manual_service_orders` (`status`,`createdAt`);--> statement-breakpoint
CREATE INDEX `manual_service_orders_payment_idx` ON `website_manual_service_orders` (`paymentOrderId`,`paymentTradeNo`);